### ISSUE TITLE
Hyperparameter optimization

### ISSUE THREAD

**Issue by yanwu2014** [theislab/cpa#10]
The provided tutorials seem to have very specific hyperparameters tuned to the dataset. Since we're interested in running CPA on new data, do you have recommendations for which hyperparemeters are key for CPA performance?

**Comment by tuln128** [comment]
Not sure if this site is still being supported. However, I have a similar question related to hyperparameter tuning for the CPA model, which has been posted here: https://github.com/theislab/cpa/issues/7#issuecomment-1260240287
Hope that some one can help make this matter clear.
Thanks in advance,

**Comment by ArianAmani** [comment]
Hyperparameter tuner added #46 
https://github.com/theislab/cpa/#how-to-optmize-cpa-hyperparamters-for-your-data
