### ISSUE TITLE
Colab error when running setup_anndata()

### ISSUE THREAD

**Issue by znavidi** [theislab/cpa#15]
Hi,

When I run the CPA colab tutorial, in the following line: 

cpa.CPA.setup_anndata(adata, 
 perturbation_keys={
 'perturbation': 'condition',
 'dosage': 'dose_val',
 },
 categorical_covariate_keys=['cell_type'],
 control_key='control',
 )

the below error occures in both tutorial:

TypeError: CategoricalDataFrameField.__init__() got an unexpected keyword argument 'obs_key'

I would appreciate any help to be able to run it.

**Comment by M0hammadL** [comment]
Hi Zeinab, thanks for your interest; we are updating the code and adding new tutorials. Hopefully,  we will have the next update by the end of the week or early next week.

**Comment by znavidi** [comment]
Thanks a lot for your prompt reply! Looking forward to it!

**Comment by sumeer1** [comment]
Hi,

Is there any update on this? I am getting the same error
