### ISSUE TITLE
Run CPA on Kang et al dataset without dosage information

### ISSUE THREAD

**Issue by znavidi** [theislab/cpa#16]
Hello,
Thank you for your contribution to the field! I'm interested in training and testing CPA on the Kang et al. (PBMC) dataset. As far as I understand, this dataset doesn't include dosage information, and the data file isn't provided on the website either. Using the PBMC file provided on the scGen website, I was wondering if you could guide me on how to run the following line without the 'dosage' information, as it throws a **KeyError: 'dosage'** when I remove the **'dosage': 'dose_val'** line.

> cpa.CPA.setup_anndata(adata, 
>                       perturbation_keys={
>                           'perturbation': 'condition',
>                           'dosage': 'dose_val',
>                       },
>                       categorical_covariate_keys=['cell_type'],
>                       control_key='control',
>                      )

Thanks in advance!

**Comment by Naghipourfar** [comment]
Hi @znavidi,

So sorry for the late response. We've just added a demo notebook to train CPA on the Kang et al dataset. Please see [here](https://cpa-tools.readthedocs.io/en/latest/tutorials/Kang.html). 

Thanks

**Comment by znavidi** [comment]
Thanks for your update!
When I run the tutorial, I get the following error, which seems to be from the data file. Would you please help with that?
<img width="998" alt="Screenshot 2023-09-11 at 8 12 26 PM" src="https://github.com/theislab/cpa/assets/48607956/098f4b02-ab82-401e-9be5-99bcbcd04e92">

Thanks!

**Comment by ArianAmani** [comment]
Hi @znavidi 
The latest version [here](https://cpa-tools.readthedocs.io/en/latest/tutorials/Kang.html) will be working properly.
Until this version gets released on pypi, please change line 3 in the first code block in the notebook from `branch = "stable"` to `branch = "not-stable"` so it will install the latest version directly from github.

Thanks
