### ISSUE TITLE
ImportError due to torchmetrics

### ISSUE THREAD

**Issue by mdmanurung** [theislab/cpa#2]
Dear authors,

I received the following error when importing `cpa`:
<details>
  <summary>Click to expand!</summary>
  
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_4076984/2672872602.py in <module>
----> 1 import cpa
      2 import scanpy as sc

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/cpa/__init__.py in <module>
      3 warnings.simplefilter('ignore')
      4 
----> 5 from ._model import CPA
      6 from ._module import CPAModule
      7 from . import _plotting as pl

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/cpa/_model.py in <module>
      7 import pandas as pd
      8 import torch
----> 9 from pytorch_lightning.callbacks import EarlyStopping
     10 from scvi.data import setup_anndata, register_tensor_from_anndata, transfer_anndata_setup, get_from_registry
     11 from scvi.data._anndata import _check_anndata_setup_equivalence

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/pytorch_lightning/__init__.py in <module>
     18 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     19 
---> 20 from pytorch_lightning import metrics  # noqa: E402
     21 from pytorch_lightning.callbacks import Callback  # noqa: E402
     22 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/pytorch_lightning/metrics/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from pytorch_lightning.metrics.classification import (  # noqa: F401
     16     Accuracy,
     17     AUC,

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.classification.auc import AUC  # noqa: F401
     16 from pytorch_lightning.metrics.classification.auroc import AUROC  # noqa: F401

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py in <module>
     16 from torchmetrics import Accuracy as _Accuracy
     17 
---> 18 from pytorch_lightning.metrics.utils import deprecated_metrics
     19 
     20 

/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/pytorch_lightning/metrics/utils.py in <module>
     20 from torchmetrics.utilities.data import dim_zero_mean as _dim_zero_mean
     21 from torchmetrics.utilities.data import dim_zero_sum as _dim_zero_sum
---> 22 from torchmetrics.utilities.data import get_num_classes as _get_num_classes
     23 from torchmetrics.utilities.data import select_topk as _select_topk
     24 from torchmetrics.utilities.data import to_categorical as _to_categorical

ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/exports/para-lipg-hpc/mdmanurung/conda/envs/cpa-env/lib/python3.7/site-packages/torchmetrics/utilities/data.py)

</details>

This seems to be caused by broken `torchmetrics`. I have tried downgrading `torchmetrics` to version `0.6.0` as shown [here](https://github.com/NVIDIA/DeepLearningExamples/issues/1113), but it did not fix the problem. I would greatly appreciate if you could solve this issue.

Thanks in advance.

Regards,
Mikhael

**Comment by Naghipourfar** [comment]
Hi,

Seems like the problem is with the version of `pytorch_lightning`. Which version are you using?

**Comment by mdmanurung** [comment]
Hi, I am using version 1.3.8. When I tried importing `pytorch_lightning` the same problem occurs!

**Comment by adamgayoso** [comment]
Think I found the issue here:

https://github.com/scverse/scvi-tools/issues/1540#issuecomment-1126324072

**Comment by adamgayoso** [comment]
also as an aside, @Naghipourfar this code here will not be sustainable with the current pinning of scvi-tools (issues like this will persist in the future).

**Comment by M0hammadL** [comment]
@adamgayoso   any suggestion to adapt it?

**Comment by adamgayoso** [comment]
`setup_anndata` needs to be updated to use our new object-oriented implementation

https://github.com/theislab/cpa/blob/b62895111dc5f31e2f8ef2d644653a8a45abe9c8/cpa/_model.py#L136

It should be straightforward
