### ISSUE TITLE
v0.5 "ValueError: Expected a parent" in tutorial

### ISSUE THREAD

**Issue by AxKo** [theislab/cpa#20]
Hello Everybody,

I tried to follow the SciPlex2 tutorial with the new version 0.5.
After adjusting ae_hparams and trainer_params I call model.train() and the CPA crashes with "ValueError: Expected a parent".

Some debugging shows that the problem is in _validate_callbacks_list() when the is_overridden() method is called on the EarlyStopping callback. Since is_overridden() is called with 'parent=None' and there is no code to set 'parent' for an EarlyStopping instance the ValueError is raised.

What am I doing wrong?

Any help is appreciated,
     Axel

**Comment by znavidi** [comment]
I have the same issue! Would appreciate any guidance.
