### ISSUE TITLE
very different results from the notebook

### ISSUE THREAD

**Issue by bitcometz** [theislab/cpa#3]
hello，

I am trying to redo the notebook：

https://cpa-tools.readthedocs.io/en/latest/tutorials/GSM.html

But I got very different results from the notebook using the same data as inputs and the same code, For example:

my results:

![1655719646018_EAC31BF5-C6EA-43df-AF1D-3E3AF823AFC2](https://user-images.githubusercontent.com/13601652/174697528-8745cfb7-d3b5-4948-ac4a-81e0f450746a.png)

the notebook:
![image](https://user-images.githubusercontent.com/13601652/174697582-7f6bdd7b-e6b0-4e3f-a922-5d2b78fe6859.png)

my results:
![1655719653499_7A78F9F2-FB74-4ef4-8584-2727A08031CC](https://user-images.githubusercontent.com/13601652/174697606-f93b0c2d-27c8-43d6-a10c-ca26d269d252.png)

the notebook:

![image](https://user-images.githubusercontent.com/13601652/174697637-955b42f8-836e-4e81-aa7c-dbe05391973a.png)

Could you help with this problem ? 
Thanks !!!

**Comment by Naghipourfar** [comment]
Hi @bitcometz,

Thanks for letting us know. I'm very sorry for the late response. I will publish the notebook with the new hyper-parameter setting for our experiments ASAP.

**Comment by bitcometz** [comment]
Thanks !!!

**Comment by Naghipourfar** [comment]
Hi @bitcometz, 

Just released a new version for the package with slight changes in input arguments and API in general. Also the tutorial notebooks are updated with latest API and hyper-parameter configuration. So I believe you can reproduce the results just by running the notebooks. Thanks very much for your patience. Please let me know if the issue still exists. 

Best,
Mohsen
