### ISSUE TITLE
The code is licensed for Yosef Lab

### ISSUE THREAD

**Issue by VPetukhov** [theislab/cpa#44]
The [license text](https://github.com/theislab/cpa/blob/7cda37e9cca2078af1b2373dc6f9422a5bc6f87d/LICENSE) claims "Copyright (c) 2021, Yosef Lab". Is Nir Yosef actually the copyright holder there? He isn't in the paper author list...

**Comment by ArianAmani** [comment]
Thank you for pointing it out. It's now fixed with the correct license reference.
