### ISSUE TITLE
Failed to run the notebook in colab

### ISSUE THREAD

**Issue by bitcometz** [theislab/cpa#5]
hello,
Thanks for develop the cpa software.

But I cannot run the [provided notebook](https://cpa-tools.readthedocs.io/en/latest/tutorials/GSM.html) in colab due to the failed installation of CPA.

Could you help with this problem ?

Thanks !!!

**Comment by Naghipourfar** [comment]
Hi @bitcometz,

Can you please try now with the latest CPA version (v0.3.3)?

**Comment by bitcometz** [comment]
Thanks and sorry for late reply，I will try ！！！

Best
