### ISSUE TITLE
Batch correction in expression space data set unavailable

### ISSUE THREAD

**Issue by fabi-lab** [theislab/cpa#52]
Hello,

I am trying to reproduce the results from the [Batch_correction_in_expression_space.ipynb] file but it appears that the data set cannot be downloaded using the presented Google Drive link.

Can I receive an updated link?

Thanks in advance,
Fabi

**Comment by ArianAmani** [comment]
Hi Fabi, thanks for your interest in CPA.
Thanks for letting us know, I will update the notebook asap with the new link to the dataset, but in the meantime, you can download the dataset from the original source using:

```
!wget --content-disposition https://figshare.com/ndownloader/files/25717328
adata = sc.read('Immune_ALL_human.h5ad')
```
