### ISSUE TITLE
CPA environment issues

### ISSUE THREAD

**Issue by lquvatexas** [theislab/cpa#58]
After I installed cpa, and when I imported cpa it gave me errors like "ModuleNotFoundError: No module named 'pkg_resources._vendor'", do you know how can we solve this? Tried different approaches, still didn't work. Thanks!

**Comment by ArianAmani** [comment]
Thanks for your interest in CPA.
I believe this issue and this comment will help you: https://github.com/theislab/cpa/issues/51#issuecomment-2288523791
Installing the new version of CPA in a fresh environment should fix the problem.
More specifically, I believe this is will fix the error you are getting:
```
pip install setuptools==70.0.0
```

**Comment by lquvatexas** [comment]
Thank you very much! It worked!
