### ISSUE TITLE
The versions for scvi-tools for CPA

### ISSUE THREAD

**Issue by bitcometz** [theislab/cpa#6]
Hello,
I have installed the CPA software but I found the results very different from the published.
I think it is due to that I have installed the latest version of scvi-tools.
Could you please provide the specific version of scvi-tools used in this software ?

Best

**Comment by Naghipourfar** [comment]
Hi @bitcometz,

Could you please install the latest version again? Just released v0.3.0 which is compatible with latest version of scvi-tools. 

Thanks,
Mohsen

**Comment by bitcometz** [comment]
Thanks !!!
