### ISSUE TITLE
Errors in running notebook

### ISSUE THREAD

**Issue by wershofe** [theislab/cpa#7]
Hello
When trying to run the notebook I run into a few problems:
1) 
cpa.CPA.setup_anndata(adata, 
                      drug_key='condition',
                      dose_key='dose_val',
                      categorical_covariate_keys=['cell_type'],
                      control_key='control',
                      combinatorial=True,
                     )
TypeError: register_fields() got unexpected keyword arguments {'combinatorial': True} passed without a source_registry.

2) 
model = cpa.CPA(adata=adata, 
                n_latent=256,
                loss_ae='gauss',
                doser_type='logsigm',
                split_key='split',
                **ae_hparams,
               )
TypeError: __init__() missing 1 required positional argument: 'n_cat_list'

Are you able to provide solutions?
Thank you

**Comment by yanwu2014** [comment]
I'm also running into this issue, seems like `VanillaEncoder` and `DecoderNormal` expect `n_cat_list` as a parameter with no default value specified?

**Comment by Naghipourfar** [comment]
Hi, 
Just published a new version with this issue fixed recently. Tutorials are also updated with the latest API. Sorry for the inconvenience. Please let me know if anything goes wrong.

**Comment by yanwu2014** [comment]
Awesome it's working for me now!

**Comment by tuln128** [comment]
> Hi, Just published a new version with this issue fixed recently. Tutorials are also updated with the latest API. Sorry for the inconvenience. Please let me know if anything goes wrong.

Hello Naghipourfar,
In the updated tutorial notebooks, it seems the **trainer_params** is assigned with random values (following is the example from GSM file:

_trainer_params = {
    'n_epochs_warmup': 5,
    'adversary_lr': 0.0008847032648856746,
    'adversary_wd': 9.629190571404551e-07,
    'adversary_steps': 3,
    'autoencoder_lr': 0.0007208558788012054,
    'autoencoder_wd': 1.2280838320404273e-07,
    'dosers_lr': 0.0008835011062896268,
    'dosers_wd': 5.886005123780177e-06,
    'penalty_adversary': 63.44954424334805,
    'reg_adversary': 48.73324753854268,
    'cycle_coeff': 7.19539336141403,
    'step_size_lr': 25,
}_). 

I am wondering how these hyperparameter values were chosen, randomly or by optimized tuning)? In the latter case, could you please share how hyperparameter tuning was conducted for CPA model?

Thank you very much, and I look forward to your feedback.
Kind regards,

**Comment by ArianAmani** [comment]
Hyperparameter tuner added #46 
https://github.com/theislab/cpa/#how-to-optmize-cpa-hyperparamters-for-your-data
